package store

import (
	"time"
)

// SecurityAlert is a raised anomaly signal: who triggered it, which detection
// rule fired, and a human-readable explanation. Alerts are generated by the
// behavior-detection engine as it observes the audit stream, and persisted so
// admins can triage them later.
type SecurityAlert struct {
	ID        string    `json:"id"`
	TS        time.Time `json:"ts"`
	Level     string    `json:"level"`     // warning | critical
	Rule      string    `json:"rule"`      // repeated_denied | bulk_export | off_hours
	Principal string    `json:"principal"` // username that triggered the alert
	Channel   string    `json:"channel"`   // dataapi | mcp
	Detail    string    `json:"detail"`
	Resolved  bool      `json:"resolved"`
}

// SecurityAlertFilter narrows ListSecurityAlerts results. Zero values mean
// "no filter". Resolved: "" = all, "open" = unresolved, "resolved" = resolved.
type SecurityAlertFilter struct {
	Level    string
	Resolved string
	Limit    int
	Offset   int
}

func (s *Store) InsertSecurityAlert(a *SecurityAlert) error {
	if a.ID == "" {
		a.ID = uid()
	}
	if a.TS.IsZero() {
		a.TS = time.Now()
	}
	if a.Resolved {
		// callers should persist as unresolved; ResolveSecurityAlert flips it
	}
	_, err := s.db.Exec(
		`INSERT INTO security_alerts (id,ts,level,rule,principal,channel,detail,resolved)
		 VALUES (?,?,?,?,?,?,?,0)`,
		a.ID, a.TS, a.Level, a.Rule, a.Principal, a.Channel, a.Detail)
	return err
}

// ListSecurityAlerts returns newest-first alerts matching the filter plus the
// total match count for pagination.
func (s *Store) ListSecurityAlerts(f SecurityAlertFilter) ([]*SecurityAlert, int, error) {
	where := ` WHERE 1=1`
	args := []interface{}{}
	if f.Level != "" {
		where += ` AND level=?`
		args = append(args, f.Level)
	}
	if f.Resolved == "open" {
		where += ` AND resolved=0`
	} else if f.Resolved == "resolved" {
		where += ` AND resolved=1`
	}

	total := 0
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM security_alerts`+where, args...).Scan(&total); err != nil {
		return nil, 0, err
	}

	limit := f.Limit
	if limit <= 0 || limit > 500 {
		limit = 50
	}
	q := `SELECT id,ts,level,rule,principal,channel,detail,resolved
	      FROM security_alerts` + where + ` ORDER BY ts DESC LIMIT ? OFFSET ?`
	args = append(args, limit, f.Offset)

	rows, err := s.db.Query(q, args...)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()
	out := []*SecurityAlert{}
	for rows.Next() {
		a := &SecurityAlert{}
		var resolved int
		if err := rows.Scan(&a.ID, &a.TS, &a.Level, &a.Rule, &a.Principal, &a.Channel, &a.Detail, &resolved); err != nil {
			return nil, 0, err
		}
		a.Resolved = resolved != 0
		out = append(out, a)
	}
	return out, total, nil
}

// ResolveSecurityAlert marks an alert as handled.
func (s *Store) ResolveSecurityAlert(id string) error {
	_, err := s.db.Exec(`UPDATE security_alerts SET resolved=1 WHERE id=?`, id)
	return err
}

// SecurityAlertStats returns quick counters for the alert dashboard.
func (s *Store) SecurityAlertStats() (map[string]int, error) {
	stats := map[string]int{"total": 0, "warning": 0, "critical": 0, "open": 0, "resolved": 0}
	rows, err := s.db.Query(`SELECT level, resolved, COUNT(*) FROM security_alerts GROUP BY level, resolved`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		var level string
		var resolved int
		var n int
		if err := rows.Scan(&level, &resolved, &n); err != nil {
			return nil, err
		}
		stats["total"] += n
		stats[level] += n
		if resolved != 0 {
			stats["resolved"] += n
		} else {
			stats["open"] += n
		}
	}
	return stats, nil
}
